Route based template
kaliberjs/build pull request #250
Opened 2023-05-26 10:29 UTC by peeke

Dit zijn je eigen code-change, maar even als plek voor discussie. Ik zou deze change heel graag hebben voor https://github.com/Kaliber/digital-power/pull/362 en voor de oude browser pagina voor de kaliber-website (en wellicht daarna voor het template)

2023-05-26 13:57 UTC, EECOLOR requested changes

2023-05-26 13:57 UTC, EECOLOR commented on library/lib/serve.js
> +      const indexPath = resolve(...[target, publicPathDir, indexLocation, indexWithRouting])
```suggestion
      const indexPath = resolve(target, publicPathDir, indexLocation, indexWithRouting)
```

2023-05-26 13:57 UTC, EECOLOR commented on library/lib/serve.js
> +      const indexLocation = routes.resolveIndex(location, req)
```suggestion
      const indexLocation = routes.resolveIndex(location, req)
      if (!indexLocation) return [data, routeTemplate]

```

2023-05-26 13:57 UTC, EECOLOR commented on example/src/routeBasedTemplate/index.html.js
> +      'routeBasedTemplate'
```suggestion
     null
```

2023-05-26 13:57 UTC, EECOLOR commented on example/src/routeBasedTemplate/index.html.js
> +  resolveIndex({ pathname }) {
Is wat makkelijker als we het meteen als documentatie willen zien
```suggestion
  resolveIndex(location, req) {
    const { pathname } = location
```

2023-06-06 08:19 UTC, peeke commented on example/src/routeBasedTemplate/index.html.js
> +    }
```suggestion
    return { status: 200, data: { hostname: request.hostname, pathname } }
```

2023-08-02 08:17 UTC, merged